Update the CrateDB Docker image homepage
docker-library/docs pull request #1905
Opened 2021-03-31 20:34 UTC by norosa

Specifically:

- Update wording to reflect the `crate/crate` `README.rst` file
- Adds some small copyedits
- Adds a link to the screenshot we use

2021-03-31 20:41 UTC, tianon commented
I'll also add a CC to [the `crate` image maintainers](https://github.com/docker-library/official-images/blob/30cd68b60db0ae340832eb691bb1002745c8cdd9/library/crate#L1-L4) for further content review: @mfussenegger @seut @mkleen @amotl

2021-03-31 20:42 UTC, norosa commented
@tianon I deleted the old PR because I thought I'd pushed it from my personal fork. perhaps I was mistaken. I will edit the short description

2021-03-31 20:51 UTC, norosa commented
@tianon I believe I have resolved the issue now

for some reason, I am having a lot of trouble rebasing locally. I think I borked my client config when I was trying to update our fork. fortunately, the GitHub interface allowed me to fix the "conflicts" that resulted

2021-03-31 21:13 UTC, amotl requested changes
Thanks a stack! Just a minor copyedit request from my side.

2021-03-31 21:13 UTC, amotl commented on crate/get-help.md
> +[project documentation](https://crate.io/docs/), [StackOverflow](https://stackoverflow.com/tags/crate), [support channels](https://crate.io/support/)
In order to align with https://github.com/crate/crate-admin/pull/702, I am humbly asking to update the tag on the link to Stack Overflow.

```suggestion
[project documentation](https://crate.io/docs/), [StackOverflow](https://stackoverflow.com/tags/cratedb), [support channels](https://crate.io/support/)
```

2021-03-31 21:37 UTC, amotl commented
Hi Naomi,

I noticed another thing, sorry to bother you once more.

At the ["Try CrateDB"](https://github.com/docker-library/docs/blob/f67955515354dc89b0121c1c224ea19631e6d014/crate/content.md#try-cratedb) section, can you also update the "Getting Started With CrateDB on Docker" link to point to [1] instead of [2]?

With kind regards,
Andreas.

[1] https://crate.io/docs/crate/howtos/en/latest/deployment/containers/docker.html
[2] https://crate.io/docs/crate/guide/en/latest/deployment/containers/docker.html

2021-04-01 13:37 UTC, norosa commented
@amotl the original purpose of this pr was to correct that link from [2] to [1] as [1] is the old URL and [2] is the new URL. have I got that right? I think this is good to go

2021-04-01 16:05 UTC, norosa commented
@amotl ah. I had some changes I hadn't pushed. and last time I tried, I resolved the conflicts incorrectly. phew! the changes should be complete and correct now. can you recheck please?

2021-04-01 19:00 UTC, amotl approved these changes
Thank you very much for adjusting the content, @norosa. @tianon: Good to go from my side.

2021-04-01 20:01 UTC, merged

2021-04-06 16:51 UTC, amotl commented
Thank you, @tianon and @yosifkit.