Add a new emqx image docs
docker-library/docs pull request #2032
Opened 2021-09-10 06:32 UTC by Rory-Z

2022-04-05 16:35 UTC, tianon requested changes

2022-04-05 16:35 UTC, tianon commented on emqx/content.md
> +`docker run -d --name emqx -p 18083:18083 -p 1883:1883 emqx:latest`
````suggestion
```console
$ docker run -d --name emqx -p 18083:18083 -p 1883:1883 %%IMAGE%%:latest
```
````

(Did you want to use something like `:tag` here as well?  Maybe also all the references throughout the docs here?)

2022-04-05 16:35 UTC, tianon commented on emqx/content.md
> +You can change the prefix by overriding "HOCON_ENV_OVERRIDE_PREFIX".
```suggestion
You can change the prefix by overriding `HOCON_ENV_OVERRIDE_PREFIX`.
```

2022-04-05 16:35 UTC, tianon commented on emqx/content.md
> +| EMQX_HOST | container IP   | none   | emqx node host, IP or FQDN |
```suggestion
| Options     | Default        | Mapped | Description                |
|-------------|----------------|--------|----------------------------|
| `EMQX_NAME` | container name | none   | emqx node short name       |
| `EMQX_HOST` | container IP   | none   | emqx node host, IP or FQDN |
```

2022-04-05 16:35 UTC, tianon commented on emqx/content.md
> +    emqx:latest
```suggestion
    %%IMAGE%%:latest
```

2022-04-06 01:47 UTC, Rory-Z commented
Hi, @tianon 
Thanks for your comment

2022-04-06 22:18 UTC, tianon approved these changes

2022-04-07 00:29 UTC, merged